import { AnalysisHistoryItem, PlayerColor, Coordinate } from '../types';

// Helper to format coordinates (convert 0-18 to A-T, 1-19)
const formatCoord = (c: Coordinate) => {
    const letters = "ABCDEFGHJKLMNOPQRST";
    return `${letters[c.x]}${19 - c.y}`;
};

export const generateGameRecordText = (history: AnalysisHistoryItem[]): string => {
  const date = new Date().toLocaleString();
  const sortedHistory = [...history].sort((a, b) => a.moveNumber - b.moveNumber);
  
  let content = `ZenGo (弈悟) 对局记录\n`;
  content += `日期: ${date}\n`;
  content += `总手数: ${sortedHistory.length}\n`;
  content += `----------------------------------------\n\n`;

  sortedHistory.forEach((item) => {
    const coord = formatCoord(item.coordinate);
    const player = item.player === PlayerColor.Black ? '黑方' : '白方';
    
    content += `第 ${item.moveNumber} 手: ${player} 落于 ${coord}\n`;
    
    if (item.analysis) {
        // Skip if still loading or failed (unless failed has partial info, but usually checking title helps)
        if (item.isLoading) {
             content += `[AI 正在思考中...]\n`;
        } else if (item.analysis.title === '分析失败') {
             content += `[AI 分析失败]\n`;
        } else {
            content += `AI 评价: ${item.analysis.evaluation} (评分: ${item.analysis.score})\n`;
            content += `主题: ${item.analysis.title}\n`;
            content += `局势解析: ${item.analysis.detailedAnalysis}\n`;
            
            if (item.analysis.strategicContext) {
                content += `战略研判: ${item.analysis.strategicContext}\n`;
            }
            
            if (item.analysis.josekiOrProverbs && item.analysis.josekiOrProverbs.length > 0) {
                 content += `相关的定式/谚语: ${item.analysis.josekiOrProverbs.join(', ')}\n`;
            }

            if (item.analysis.variations && item.analysis.variations.length > 0) {
                content += `推荐选点:\n`;
                item.analysis.variations.forEach((v, i) => {
                     content += `  ${i+1}. ${formatCoord(v.move)} - ${v.explanation} (评分: ${v.score})\n`;
                });
            }
        }
    }
    content += `\n----------------------------------------\n\n`;
  });

  content += `\nGenerated by ZenGo (弈悟)`;
  return content;
};

export const downloadGameRecord = (history: AnalysisHistoryItem[]) => {
    if (history.length === 0) {
        alert("暂无对局记录可导出");
        return;
    }
    const text = generateGameRecordText(history);
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    // Format: zengo_game_YYYY-MM-DD_HH-mm-ss.txt
    const now = new Date();
    const timestamp = `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}_${String(now.getHours()).padStart(2,'0')}-${String(now.getMinutes()).padStart(2,'0')}-${String(now.getSeconds()).padStart(2,'0')}`;
    link.download = `zengo_game_${timestamp}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};
